# Writes ForkVersion.h: this fork's build number, counted as commits since
# the upstream commit it branched from (repo-root FORK_BASE), plus the short
# HEAD hash and a dirty flag. The upstream VERSION stays as the "based on"
# number. Run as a script on every build (see plugin/CMakeLists.txt) so the
# number never goes stale; the header is only rewritten when it changes, so
# an unchanged checkout doesn't trigger a recompile.
#
#   cmake -DSRC_DIR=<repo root> -DOUT=<header path> -P ForkVersion.cmake

file(READ "${SRC_DIR}/FORK_BASE" _base)
string(STRIP "${_base}" _base)
file(READ "${SRC_DIR}/VERSION" _upstream)
string(STRIP "${_upstream}" _upstream)

set(_build 0)
set(_hash "unknown")
set(_dirty 0)
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-list --count "${_base}..HEAD"
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _out RESULT_VARIABLE _rc
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_rc EQUAL 0)
        set(_build "${_out}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=7 HEAD
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _out RESULT_VARIABLE _rc
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_rc EQUAL 0)
        set(_hash "${_out}")
    endif()
    # Tracked files only: untracked scratch (docs, zips) shouldn't mark the
    # build as modified.
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _out RESULT_VARIABLE _rc
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_rc EQUAL 0 AND NOT _out STREQUAL "")
        set(_dirty 1)
    endif()
endif()

set(_content "// Generated by cmake/ForkVersion.cmake - do not edit.
#pragma once
#define T3K_FORK_BUILD ${_build}
#define T3K_FORK_HASH \"${_hash}\"
#define T3K_FORK_DIRTY ${_dirty}
#define T3K_UPSTREAM_VERSION \"${_upstream}\"
")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
else()
    set(_old "")
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
